Learnigo.WebUI/Areas/Admin/Controllers/BannerController.cs
using Learnigo.WebUI.Dtos.BannerDtos;
using Learnigo.WebUI.Helpers;
using Microsoft.AspNetCore.Mvc;

namespace Learnigo.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("[area]/[controller]/[action]/{id?}")]
    public class BannerController : Controller
    {
        

        private readonly HttpClient _client = HttpClientInstance.CreateClient();
        public async Task<IActionResult> Index()
        {
            var value = await _client.GetFromJsonAsync<List<ResultBannerDto>>("banners");
            return View(value);
        }

        public async Task<IActionResult> DeleteBanner(int id)
        {
            await _client.DeleteAsync($"banners/{id}");
            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateBanner()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> CreateBanner(CreateBannerDto createBannerDto)
        {
            await _client.PostAsJsonAsync("banners", createBannerDto);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UpdateBanner(int id)
        {
            var value = await _client.GetFromJsonAsync<UpdateBannerDto>($"banners/{id}");
            return View(value);
        }

        [HttpPost]

        public async Task<IActionResult> UpdateBanner(UpdateBannerDto updateBannerDto)
        {
            await _client.PutAsJsonAsync("banners", updateBannerDto);
            return RedirectToAction(nameof(Index));
        }
    }
}

Learnigo.WebUI/Areas/Admin/Views/Banner/CreateBanner.cshtml
@model CreateBannerDto
@{
    ViewData["Title"] = "Yeni Banner Ekleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
    <label>Resim Url</label>
	<input type="text" asp-for="ImageUrl" class="form-control" />
    <br />
	<label>Başlık</label>
	<input type="text" asp-for="title" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Kaydet</button>

</form>

Learnigo.WebUI/Areas/Admin/Views/Banner/Index.cshtml
@model List<ResultBannerDto>
@{
    ViewData["Title"] = "Banner Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
	int count = 0;
}


<table class="table table-hover">
	<tr>
		<th>#</th>
		<th>Başlık</th>
		
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		count++;
		<tr>
			<th>@count</th>
			<td> <img src=" @item.ImageUrl" style="height:75px; width:75px;" /> @item.title </td>
			

			<td>
				<a asp-action="DeleteBanner" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-danger">Sil</a>
				<a asp-action="UpdateBanner" asp-controller="Banner" asp-area="Admin" asp-route-id="@item.BannerId" class="btn btn-outline-info">Güncelle</a>

			</td>

		</tr>
	}

</table>

<br />
<a asp-action="CreateBanner" asp-controller="Banner" asp-area="Admin" class="btn btn-outline-primary">Yeni Banner Ekle</a>

Learnigo.WebUI/Areas/Admin/Views/Banner/UpdateBanner.cshtml
@model UpdateBannerDto
@{
    ViewData["Title"] = "Banner Güncelleme Sayfası";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<form method="post">
	<input type="hidden" asp-for="BannerId" />
	<label>Resim Url</label>
	<input type="text" asp-for="ImageUrl" class="form-control" />
	<br />
	<label>Başlık</label>
	<input type="text" asp-for="title" class="form-control" />
	<br />
	<button class="btn btn-outline-primary">Güncelle</button>

</form>